config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :subscriptions do
      resource :customer, :controller => "subscriptions/customer_details"
    end
    resources :products, :as => :samplebox do
      resources :issues, :controller => "products/issues"
      match "issues/:id/ship", :to => "products/issues#ship", :via => :get, :as => :issue_ship
    end
    resources :users # Hack to make tests pass
  end
  resources :sampleboxes, :to => "sampleboxes#index"
end

app/models/spree/issue.rb
class Spree::Issue < ActiveRecord::Base
  
  # reverse one-to-one with samplebox Spree::Product
  belongs_to :samplebox, :class_name => "Spree::Product"
  belongs_to :samplebox_issue, :class_name => "Spree::Product"

  # composed of shipped # of issues and the content sample products
  has_many :shipped_issues

  # TODO: keep track of how this works out
  # has_many :sample_product, :class_name => "Spree:Product"

  attr_accessible :name, :published_at, :shipped_at, :samplebox, :samplebox_issue_id
  
  # expose the implementation of :subscription, but define it in :samplebox
  delegate :subscriptions,:to => :samplebox

  # TODO: figure out what this is doing
  validates :name, 
    :presence => true,
    :unless => "samplebox_issue.present?"

  def name
    samplebox_issue.present? ? samplebox_issue.name : read_attribute(:name)
  end
  
  # read eligible_for_shipping scope of each subscription.
  # ship! them. 
  # then update all the shipping dates to time of this function call
  def ship!
    subscriptions.eligible_for_shipping.each{ |s| s.ship!(self) }
    update_attribute(:shipped_at, Time.now)
  end

  def shipped?
    !shipped_at.nil?
  end

end

app/controllers/spree/admin/products/issues_controller.rb
module Spree
  module Admin
    module Products
      class IssuesController < Spree::Admin::BaseController
        before_filter :load_samplebox
        before_filter :load_issue, :only => [:show, :edit, :update, :ship]
        before_filter :load_product, :except => [:show, :index]

        def show
          if @issue.shipped?
            @product_subscriptions = @issue.shipped_issues.map { |shipped_issue| shipped_issue.subscription }.compact
          else
            @product_subscriptions = Subscription.eligible_for_shipping.where(:samplebox_id => @samplebox.id)
          end
          respond_to do |format|
            format.html
            format.pdf do
              addresses_list = @product_subscriptions.map { |s| s.ship_address }
              labels = IssuePdf.new(addresses_list, view_context)
              send_data labels.document.render, :filename => "#{@issue.name}.pdf", :type => "application/pdf", disposition: "inline"
            end
          end
        end

        def index
          @issues = Issue.where(:samplebox_id => @samplebox.id)
        end

        def update
          if @issue.update_attributes(params[:issue])
            flash[:notice] = t('issue_updated')
            redirect_to admin_samplebox_issue_path(@samplebox, @issue)
          else
            flash[:error] = t(:issue_not_updated)
            render :action => :edit
          end
        end

        def new
          @issue = @samplebox.issues.build
        end

        def create
          if (new_issue = @samplebox.issues.create(params[:issue]))
            flash[:notice] = t('issue_created')
            redirect_to admin_samplebox_issue_path(@samplebox, new_issue)
          else
            flash[:error] = t(:issue_not_created)
            render :new
          end
        end

        def ship
          if @issue.shipped?
            flash[:error]  = t('issue_not_shipped')
          else
            @issue.ship!
            flash[:notice]  = t('issue_shipped')
          end
          redirect_to admin_samplebox_issues_path(@samplebox, @issue)
        end

        private

        def load_samplebox
          @samplebox = Product.find_by_permalink(params[:samplebox_id])
          @product = @samplebox # useful to display product_tab menu
        end

        def load_issue
          @issue = Issue.find(params[:id])
        end

        def load_product
          @products = Product.unsubscribable.map { |product| [product.name, product.id] }
        end
      end
    end
  end
end

app/views/spree/admin/products/issues/_form.html.erb
<h3><%= t(:issue).titleize %></h3>

<%= render 'issue_fields', :f => f %>  

app/views/spree/admin/products/issues/_issue_fields.html.erb
 <fieldset>
  <%= f.label :name, t(:name, :scope => 'activerecord.attributes.spree/subscription') %>
  <%= f.text_field :name %>

  <%= f.label :samplebox_issue_id, t(:product) %>
  <%= f.select :samplebox_issue_id, @products, :include_blank => true %>
</fieldset>

app/views/spree/admin/products/issues/_samplebox_issue.html.erb
<div class="clearfix samplebox_issue">
  <%= product_image(product) %>
  <h2><%= t(:description) %></h2>
  <%= truncate(product.description, :length => 400) %>
</div>

app/views/spree/admin/products/issues/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Issues' } %>

<%= csrf_meta_tags %>

<div data-hook="admin_product_issue_edit_header">
  <h2><%= t("editing_issue") %></h2>
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @samplebox } %>
</div>

<div data-hook="admin_product_issue_edit_form">
  <div id="issue-form-wrapper">
    <%= form_for [@samplebox, @issue], :url => admin_samplebox_issue_url(@samplebox, @issue) do |f| %>
      <%= render 'form', :f => f  %>

      <p class="form-buttons" data-hook="buttons">
     	  <%= button t(:update) %>
      </p>
    <% end %>
  </div>
</div>

app/views/spree/admin/products/issues/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Issues' } %>

<div class="toolbar" data-hook="toolbar">
  <ul class="actions">
    <li id="new_issue_link">
    <%= button_link_to t(:new_issue), new_admin_samplebox_issue_url(@samplebox), { :icon => 'add', :id => 'admin_new_issue' } %>
    </li>
  </ul>
  <br class="clear" />
</div>

<h1><%= t("listing_issues") %></h1>

<table class="index" id="listing_issues">
  <thead>
    <tr>
      <th><%= t(:name, :scope => 'activerecord.attributes.spree/issue') %></th>
      <th><%= t(:shipped_at, :scope => 'activerecord.attributes.spree/issue') %></th>
      <th data-hook="admin_issues_index_header_actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= link_to issue.name, admin_samplebox_issue_url(@samplebox, issue) %></td>
        <td><%= issue.shipped? ? issue.shipped_at.to_s(:db) : t(:issue_not_shipped) %></td>
        <td class="actions" data-hook="admin_issues_index_row_actions">
          <%= link_to_with_icon :accept, t(:ship).capitalize, admin_samplebox_issue_ship_path(@samplebox, issue), :confirm => t(:are_you_sure) if !issue.shipped? %>
          <%= link_to_with_icon :edit,  t(:edit), edit_admin_samplebox_issue_url(@samplebox, issue), :class => 'edit' if !issue.shipped? %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/products/issues/new.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Issues' } %>

<%= csrf_meta_tags %>

<div data-hook="admin_product_issue_new_header">
  <h2><%= t("creating_issue") %></h2>
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @samplebox } %>
</div>

<div data-hook="admin_product_issue_new_form">
  <div id="issue-form-wrapper">
    <%= form_for [@samplebox, @issue], :url => admin_samplebox_issues_path(@samplebox), :method => :post do |f| %>
      <%= render 'form', :f => f  %>

      <p class="form-buttons" data-hook="buttons">
        <%= button t(:create) %>
		  </p>
    <% end %>
  </div>
</div>

app/views/spree/admin/products/issues/show.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Issues' } %>

<div data-hook="admin_product_issue_header">
  <h2><%= @issue.name %></h2>
</div>

<% if @issue.samplebox_issue %>
  <%= render 'samplebox_issue', :product => @issue.samplebox_issue %>
<% end %>

<div class="toolbar" data-hook="admin_issue_show_buttons">
  <%= button_link_to t(:ship), admin_samplebox_issue_ship_path(@product, @issue), :icon => 'accept', :confirm => t(:are_you_sure) if !@issue.shipped? %>
  <%= button_link_to t(:print), admin_samplebox_issue_path(@product, @issue, :format => :pdf), :icon => 'pdf' %>
</div>
<br class="clear">
<br>

<h1><%= @issue.shipped? ? t(:shipped_to) : t(:subscribed) %></h1>

<table class="index" id="subscriptions_listing">
  <thead data-hook="admin_subscriptions_index_headers">
    <th><%= t(:email) %></th>
    <th><%= t(:first_name) %></th>
    <th><%= t(:last_name) %></th>
    <th><%= t(:street_address) %></th>
    <th><%= t(:zip) %></th>
    <th><%= t(:city) %></th>
    <th><%= t(:state) %></th>
    <th><%= t(:phone) %></th>
  </thead>
  <tbody>
    <% @product_subscriptions.each do |subscription|%>
      <tr id="<%= spree_dom_id subscription %>" data-hook="admin_subscriptions_index_rows">
        <td><%= subscription.email %></td>
        <td><%= subscription.ship_address.firstname %></td>
        <td><%= subscription.ship_address.lastname %></td>
        <td>
          <%= subscription.ship_address.address1 %>
          <%= raw("</br>#{subscription.ship_address.address2}") if subscription.ship_address.address2.present? %>
        </td>
        <td><%= subscription.ship_address.zipcode %></td>
        <td><%= subscription.ship_address.city %></td>
        <td><%= subscription.ship_address.state_name %></td>
        <td><%= subscription.ship_address.phone %></td>
      </tr>
    <% end %>
  </tbody>
</table>